apiVersion: "kubeflow.org/v1"
kind: "TFJob"
metadata:
  name: "dgl-dist-kvstore-test"
spec:
  tfReplicaSpecs:
    PS:
      replicas: 2
      restartPolicy: Never
      template:
        metadata:
          labels:
            dgl-test: dist
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: beta.kubernetes.io/instance-type
                    operator: In
                    values:
                    - m5n.24xlarge
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                    - key: dgl-test
                      operator: In
                      values:
                      - dist
                  topologyKey: kubernetes.io/hostname          
          tolerations:
            - key: dgl.ai/dedicated
              operator: "Exists"
              effect: "NoSchedule"
          hostNetwork: true
          hostPorts:
          - min: 0
            max: 65535
          dnsPolicy: ClusterFirstWithHostNet
          containers:
            - name: tensorflow
              image: public.ecr.aws/s1o7b3d9/benchmakrk_pyg_dgl:cu111_torch181_pyg170
              ports:
              - containerPort: 30051
                name: dist-port1
              - containerPort: 30050
                name: dist-port2
              args: 
              - "bash"
              - "-c"
              - |
                echo $TF_CONFIG
                wget https://dgl-data.s3.us-west-2.amazonaws.com/assets/parse_tf_config.py
                wget https://dgl-data.s3.us-west-2.amazonaws.com/assets/dist_benchmark.py
                sleep 10s
                python parse_tf_config.py
                cat ip_config.txt
                export MACHINE_ID=$(cat machine_id.txt)
                echo $MACHINE_ID
                export PYTHONUNBUFFERED=1
                pip install --pre dgl -f https://data.dgl.ai/wheels-test/repo.html
                # wget https://github.com/dglai/dgl-benchmark/raw/master/kvstore/benchmark.py
                python -c "import dgl"
                python3 dist_benchmark.py --server_id $MACHINE_ID --machine_id $MACHINE_ID & python3 dist_benchmark.py --machine_id $MACHINE_ID
    # Worker:
    #   replicas: 4
    #   restartPolicy: Never
    #   template:
    #     spec:
    #       containers:
    #         - name: tensorflow
    #           image: kubeflow/tf-dist-mnist-test:1.0